# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Using Docker
email: info@runnable.com
description: > # this means to ignore newlines until "baseurl:"
  By Runnable: The service that speeds up development by providing full-stack environments for every code branch.
url: https://runnable.com # the base hostname & protocol for your site
baseurl: /docker
twitter_username: GetRunnable
github_username:  Runnable

# Build settings
markdown: kramdown

# Output
permalink: :title

gems:
  - jekyll-seo-tag
  - jekyll-sitemap

permalink: /:categories/:title/
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: page

sass:
  sass_dir: _sass/
